### ISSUE TITLE
Consider changing dependencies

### ISSUE THREAD

**Issue by gonrial** [MauriceButler/bunyan-loggly#13]
Please consider updating the dependencies. Right now we have `node-uuid` generating warnings: ` [SECURITY] node-uuid: crypto not usable, falling back to insecure Math.random()`

Tracking back ... [loggly](https://www.npmjs.com/package/loggly) package seems to be [unmaintained](https://github.com/winstonjs/node-loggly/issues/68) (issue open five months back without answers). Loggly team created a [fork repo](https://github.com/loggly/node-loggly-bulk/) to keep up security updates and created a [new package](https://www.npmjs.com/package/node-loggly-bulk).

**Comment by JorgenEvens** [comment]
We're also having issues due to this in our code.

**Comment by auberryberry** [comment]
+1 here would be great to swap dependencies

**Comment by bilby91** [comment]
Any updates ?

**Comment by MauriceButler** [comment]
Sorry everyone I have been away for a few weeks Ill get this sorted out now.

**Comment by auberryberry** [comment]
You rock, thank you.

On 3 Oct 2017, at 11:41, Maurice Butler <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry everyone I have been away for a few weeks Ill get this sorted out now.

**Comment by MauriceButler** [comment]
FYI version 1.3.0 is now published which has been updated to use `node-loggly-bulk`.

This version should now install with no security warnings. 

Due to some missing functionality in the `node-loggly-bulk` messages will no longer be sent to loggly in bulk.

As soon as the loggly/node-loggly-bulk#21 PR is merged I will release another version to bring back the bulk sending.

I will close this issue now and have raised #18 to track the change to re-enable bulk processing
